import type { CarCardProps } from '@/types/types';
import type { CarLogo } from '@/types/types';

export const CAR_LOGOS: CarLogo[] = [
	{
		src: '/icons/Toyota.svg',
		alt: 'Toyota logo',
		width: 82,
		height: 54,
	},
	{
		src: '/icons/Ford.svg',
		alt: 'Ford logo',
		width: 115,
		height: 44,
	},
	{
		src: '/icons/Mercedes.svg',
		alt: 'Mercedes logo',
		width: 55,
		height: 54,
	},
	{
		src: '/icons/Jeep.svg',
		alt: 'Jeep logo',
		width: 109,
		height: 44,
	},
	{
		src: '/icons/Bmw.svg',
		alt: 'BMW logo',
		width: 55,
		height: 54,
	},
	{
		src: '/icons/Audi.svg',
		alt: 'Audi logo',
		width: 124,
		height: 42,
	},
];

export const POPULAR_CARS: CarCardProps[] = [
	{
		id: 'bmw-x6-1',
		image: '/images/Amg-alt.svg',
		name: 'BMW X6',
		price: 65,
		type: 'SUV',
		transmission: 'Manual',
		doors: 4,
		passengers: 4,
		hasAC: true,
	},
	{
		id: 'bmw-x6-2',
		image: '/images/Amg-alt.svg',
		name: 'BMW X6',
		price: 65,
		type: 'SUV',
		transmission: 'Manual',
		doors: 4,
		passengers: 4,
		hasAC: false,
	},
	{
		id: 'audi-a4-1',
		image: '/images/Amg-alt.svg',
		name: 'Audi A4',
		price: 45,
		type: 'Sedan',
		transmission: 'Automatic',
		doors: 4,
		passengers: 5,
		hasAC: true,
	},
	{
		id: 'bmw-x6-3',
		image: '/images/Amg-alt.svg',
		name: 'BMW X6',
		price: 65,
		type: 'SUV',
		transmission: 'Manual',
		doors: 4,
		passengers: 4,
		hasAC: true,
	},
	{
		id: 'bmw-x6-4',
		image: '/images/Amg-alt.svg',
		name: 'BMW X6',
		price: 65,
		type: 'SUV',
		transmission: 'Manual',
		doors: 4,
		passengers: 4,
		hasAC: false,
	},
	{
		id: 'audi-a4-2',
		image: '/images/Amg-alt.svg',
		name: 'Audi A4',
		price: 45,
		type: 'Sedan',
		transmission: 'Automatic',
		doors: 4,
		passengers: 5,
		hasAC: true,
	},
	{
		id: 'mercedes-c-class-1',
		image: '/images/Amg-alt.svg',
		name: 'Mercedes-Benz',
		price: 55,
		type: 'Sedan',
		transmission: 'Automatic',
		doors: 4,
		passengers: 5,
		hasAC: true,
	},
	{
		id: 'toyota-camry-1',
		image: '/images/Amg-alt.svg',
		name: 'Toyota Camry',
		price: 40,
		type: 'Sedan',
		transmission: 'Automatic',
		doors: 4,
		passengers: 5,
		hasAC: true,
	},
];
